services:
  - type: web
    name: d-admin-engine
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: ALLOWED_ORIGINS
        value: https://d-admin-drj.vercel.app
    autoDeploy: true
